### ISSUE TITLE
ERR_INVALID_ARG_TYPE error

### ISSUE THREAD

**Issue by anthr76** [lymbada/Floatplane-Downloader-Docker#1]
Hello, this looks like a great project upon my first launch I'm getting a pretty cryptic error.

```
docker run -it --name FloatPlaneTest -e PUID=1000 -e PGID=1000 -v /mnt/zfs/Storage/Media/Floatplane:/Floatplane-Downlder/videos -v ${HOME}/Docker/plex/floatplane:/Floatplane-Downloader/config lymbada/floatplane-downloader
Running run.sh startup script
Missing critical file '/Floatplane-Downloader/broken.json', you'l need this to run, creating it now
Missing critical file '/Floatplane-Downloader/float.log', you'l need this to run, creating it now
Missing critical file '/Floatplane-Downloader/videos.json.backup', you'l need this to run, creating it now
Missing critical file '/Floatplane-Downloader/partial.json', you'l need this to run, creating it now
internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.open (fs.js:408:3)
    at WriteStream.open (internal/fs/streams.js:272:12)
    at new WriteStream (internal/fs/streams.js:259:10)
    at Object.createWriteStream (fs.js:1736:10)
    at Object.<anonymous> (/Floatplane-Downloader/float.js:18:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by lymbada** [comment]
Confirmed, on the error. As I was using (updating) an existing working config I already had the 'video.json' file which exists (and is required to run). I've made some changes to both the Dockerfile & run.sh script so that it uses a different method for initial setup, it now seems to work. (bearing in-mind that in this case, you have to run it once, then add your username/password to the config/settings.json file, then run it a 2nd time).
It should now work for initial creation along with existing config file storage. (dockerhub version 6.4.3.1, currently building)

(BTW this is mostly for me to use with my URaid and using dockerhub as I don't actually know how to add a local repository or build a docker container on that platform. But hey, if it's working for you too, thats a bonus.

**Comment by anthr76** [comment]
> (BTW this is mostly for me to use with my URaid and using dockerhub as I don't actually know how to add a local repository or build a docker container on that platform. But hey, if it's working for you too, thats a bonus.

Indeed! This is a great help to me as I would love to have local access to my floatplane subscriptions without installing software on my host OS. Will test now and report back.

**Comment by anthr76** [comment]
Hmmm I still seem to receive this error. Even though I have my credentials in `settings.json`
